--lab-4--

--PART-A---

--1)Add two more columns City VARCHAR (20) and Pincode INT.
ALTER TABLE DEPOSITE
ADD CITY VARCHAR(20),PINCODE INT

SELECT *FROM DEPOSITE

--2)Change the size of CNAME column from VARCHAR (50) to VARCHAR (35).

ALTER TABLE DEPOSITE
ALTER COLUMN CNAME VARCHAR(35)

SELECT *FROM DEPOSITE 

--3) Change the data type DECIMAL to INT in amount Column

ALTER TABLE DEPOSITE
ALTER COLUMN AMOUNT INT

SELECT *FROM DEPOSITE

--4)Rename Column ActNo to ANO.

SP_RENAME 'DEPOSITE.ACTNO', 'ANO'
SELECT *FROM DEPOSITE

--5)Delete Column City from the DEPOSIT table

ALTER TABLE DEPOSITE
DROP COLUMN CITY

SELECT *FROM DEPOSITE

--6)Change name of table DEPOSIT to DEPOSIT_DETAIl

SP_RENAME 'DEPOSITE','DEPOSITE_DETAIL'

--PART-B---

--1)Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table.                                                                   
SP_RENAME 'DEPOSITE_DETAIL.ADATE','AOPENDATE'

SELECT *FROM DEPOSITE_DETAIL

--2)Delete Column AOPENDATE from the DEPOSIT_DETAIL table.

ALTER TABLE DEPOSITE_DETAIL
DROP COLUMN AOPENDATE

SELECT *FROM DEPOSITE_DETAIL

--3)Rename Column CNAME to CustomerName.
SP_RENAME 'DEPOSITE_DETAIL.CNAME','CUSTOMERNAME'

SELECT *FROM DEPOSITE_DETAIL

--PART-C---
CREATE TABLE STUDENT_DETAIL(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(20),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)
--1). Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null)

ALTER TABLE STUDENT_DETAIL
ADD CITY VARCHAR(20) NOT NULL DEFAULT 'RAJKOT',BACKLOG INT NULL
SELECT *FROM STUDENT_DETAIL

--2)Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35)

ALTER TABLE STUDENT_DETAIL
ALTER COLUMN NAME VARCHAR(35)

SELECT *FROM STUDENT_DETAIL 

--3)Change the data type DECIMAL to INT in CPI Column

ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT

SELECT *FROM STUDENT_DETAIL

--4)Rename Column Enrollment_No to ENO.

SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO'
SELECT *FROM STUDENT_DETAIL

--5)Delete Column City from the student_detail table.

ALTER TABLE STUDENT_DETAIL
DROP COLUMN CITY

SELECT *FROM STUDENT_DETAIL

--6)Change name of table student_detail to STUDENT_MASTER.
SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'

--DELETE,TRUNCATE,DROP---

--PART-A--

--1)Delete all the records of DEPOSIT_DETAIL table having amount greater than and equals to 4000

DELETE FROM DEPOSITE_DETAIL
WHERE AMOUNT>=4000

SELECT *FROM DEPOSITE_DETAIL

--2) Delete all the accounts CHANDI BRANCH.

DELETE FROM DEPOSITE_DETAIL
WHERE BNAME='CHANDI'

SELECT *FROM DEPOSITE_DETAIL

--3)Delete all the accounts having account number (ANO) is greater than 105.

DELETE FROM DEPOSITE_DETAIL
WHERE ANO>105

SELECT *FROM DEPOSITE_DETAIL

--4)Delete all the records of Deposit_Detail table

TRUNCATE TABLE DEPOSITE_DETAIL

SELECT *FROM DEPOSITE_DETAIL

--5)Remove Deposit_Detail table

DROP TABLE DEPOSITE_DETAIL

SELECT *FROM DEPOSITE_DETAIL

--PART-B---

CREATE TABLE EMPLOYEE_MASTER(
EMPNO INT,
EMPNAME VARCHAR(25),
JOININGDATE DATETIME,
SALARY DECIMAL(8,2),
CITY VARCHAR(20)
)

INSERT INTO EMPLOYEE_MASTER VALUES(101,'KEYUR','2002-1-5',12000,'RAJKOT')
INSERT INTO EMPLOYEE_MASTER VALUES(102,'HARDIK','2004-2-15',14000,'AHMEDABAD')
INSERT INTO EMPLOYEE_MASTER VALUES(103,'KAJAL','2006-3-14',15000,'BARODA')
INSERT INTO EMPLOYEE_MASTER VALUES(104,'BHOOMI','2005-6-23',12500,'AHMEDABAD')
INSERT INTO EMPLOYEE_MASTER VALUES(105,'HARMIT','2004-2-15',14000,'RAJKOT')
INSERT INTO EMPLOYEE_MASTER VALUES(106,'MITESH','2001-9-1',5000,'JAMNAGAR')
INSERT INTO EMPLOYEE_MASTER VALUES(107,'MEERA',NULL,7000,'MORBI')
INSERT INTO EMPLOYEE_MASTER VALUES(108,'KISHAN','2003-2-6',10000,NULL)

SELECT *FROM EMPLOYEE_MASTER

--1)Delete all the records of Employee_MASTER table having salary greater than and equals to 14000

DELETE FROM EMPLOYEE_MASTER
WHERE SALARY>=14000

SELECT *FROM EMPLOYEE_MASTER

--2)Delete all the Employees who belongs to ‘RAJKOT’ city

DELETE FROM EMPLOYEE_MASTER
WHERE CITY='RAJKOT'

SELECT *FROM EMPLOYEE_MASTER

--3)Delete all the Employees who joined after 1-1-2007.
DELETE FROM EMPLOYEE_MASTER
WHERE JOININGDATE>'2007-1-1'

SELECT *FROM EMPLOYEE_MASTER

--4)Delete the records of Employees whose joining date is null and Name is not null.

DELETE FROM EMPLOYEE_MASTER
WHERE JOININGDATE IS NULL AND EMPNAME IS NOT NULL

SELECT *FROM EMPLOYEE_MASTER

--5)Delete the records of Employees whose salary is 50% of 20000.

DELETE FROM EMPLOYEE_MASTER
WHERE SALARY=10000

SELECT *FROM EMPLOYEE_MASTER

--6) Delete the records of Employees whose City Name is not empty

DELETE FROM EMPLOYEE_MASTER
WHERE CITY IS NOT NULL

SELECT *FROM EMPLOYEE_MASTER

--7)Delete all the records of Employee_MASTER table

TRUNCATE TABLE EMPLOYEE_MASTER

SELECT *FROM EMPLOYEE_MASTER

--8) Remove Employee_MASTER table.

DROP  TABLE EMPLOYEE_MASTER















