--LAB-3---

--PART-A--
CREATE TABLE CRICKET(

NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
)
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('SACHIN TENDULKAR','MUMBAI',30)
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('RAHUL DRAVID','BOMBAY',35)
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('M.S. DHONI','JHARKHAND',31)				
 INSERT  INTO CRICKET  (NAME,CITY,AGE)  VALUES('SURESH RAINA','GUJRAT',30)
 SELECT *FROM CRICKET


--1) Create table Worldcup from cricket with all the columns and data.
SELECT * INTO WORLDCUP FROM CRICKET
WHERE 1=1;

SELECT *FROM WORLDCUP

--2) Create table T20 from cricket with first two columns with no data.
SELECT NAME,CITY INTO T20 FROM CRICKET
WHERE 1=2;

SELECT *FROM T20

--3) Create table IPL From Cricket with No Data
SELECT *INTO IPL FROM CRICKET
WHERE 1=2;

SELECT *FROM IPL

--PART-B---

CREATE TABLE EMPLOYEE(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
)

INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES ('JAY PATEL','RAJKOT',30)
INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES ('RAHUL DSVE','BARODA',35)
INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES ('JEET PATEL','SURAT',31)
INSERT INTO EMPLOYEE (NAME,CITY,AGE) VALUES  ('VIJAY RAVAL','RAJKOT',30)
SELECT *FROM EMPLOYEE

--1) Create table Employee_detail from Employee with all the columns and data. 
SELECT * INTO EMPLOYEE_DETAILS FROM EMPLOYEE
WHERE 1=1;

SELECT *FROM EMPLOYEE_DETAILS

--2) Create table Employee_data from Employee with first two columns with no data.
SELECT NAME,CITY INTO EMPLOYEE_DETAILS1 FROM EMPLOYEE
WHERE 1=2;

SELECT *FROM EMPLOYEE_DETAILS1

--3) Create table Employee_info from Employee with no Data
SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE
WHERE 1=2;

SELECT *FROM EMPLOYEE_INFO

--PART-C----

--1) Insert the Data into Employee_info from Employee whose CITY is Rajkot

INSERT INTO EMPLOYEE_INFO SELECT *FROM EMPLOYEE
WHERE CITY='RAJKOT'

SELECT *FROM EMPLOYEE_INFO

--2) Insert the Data into Employee_info from Employee whose age is more than 32.
INSERT INTO EMPLOYEE_INFO SELECT *FROM EMPLOYEE
WHERE AGE>32

SELECT *FROM EMPLOYEE_INFO



--UPDATE OPERATION----

--PART-A---

--1) Update deposit amount of all customers from 3000 to 5000
 UPDATE DEPOSITE
 SET AMOUNT=5000
 WHERE AMOUNT=3000
 SELECT *FROM DEPOSITE

--2) Change branch name of ANIL from VRCE to C.G. ROAD.
UPDATE BORROW
SET BNAME='C.G.ROAD'
WHERE CNAME='ANIL'
SELECT *FROM BORROW

--3) Update Account No of SANDIP to 111 & Amount to 5000
UPDATE DEPOSITE
SET ACTNO=111,AMOUNT=5000
WHERE BNAME='SANDIP'
SELECT *FROM DEPOSITE

--4) Update amount of KRANTI to 7000
UPDATE DEPOSITE
SET AMOUNT=7000
WHERE CNAME='KRANTI'
SELECT *FROM DEPOSITE

--5) Update branch name from ANDHERI to ANDHERI WEST
UPDATE DEPOSITE
SET BNAME='ANDHERI WEST'
WHERE BNAME='ANDHERI'
SELECT *FROM DEPOSITE

--6) Update branch name of MEHUL to NEHRU PALACE.

SELECT *FROM DEPOSITEUPDATE DEPOSITE
SET BNAME='NEHRU PALACE'
WHERE CNAME='MEHUL'
SELECT *FROM DEPOSITE

--7) Update deposit amount of all depositors to 5000 whose account no between 103 & 107
UPDATE DEPOSITE
SET AMOUNT=5000
WHERE ACTNO BETWEEN 103 AND 107
SELECT *FROM DEPOSITE

--8) Update ADATE of ANIL to 1-4-95
UPDATE DEPOSITE
SET ADATE='1995-4-1'
WHERE CNAME='ANIL'

--9) Update the amount of MINU to 10000.
UPDATE DEPOSITE
SET AMOUNT=10000
WHERE CNAME='MINU'
SELECT *FROM DEPOSITE

--10) Update deposit amount of PRAMOD to 5000 and ADATE to 1-4-96
UPDATE DEPOSITE
SET AMOUNT=5000,ADATE='1996-4-1'
WHERE CNAME='PRAMOD'
SELECT *FROM DEPOSITE

--PART-B---

--1) Give 10% Increment in Loan Amount
UPDATE BORROW
SET AMOUNT=AMOUNT+(AMOUNT)*0.10
SELECT * FROM BORROW
 
--2) Customer deposits additional 20% amount to their account, update the same
UPDATE DEPOSITE
SET AMOUNT=AMOUNT+(AMOUNT)*0.20
SELECT *FROM DEPOSITE

--PART-C---

--1) Update amount of loan no 321 to NULL.
UPDATE BORROW
SET AMOUNT=NULL
WHERE LOANNO=321
SELECT *FROM BORROW

--2) Update branch name of KRANTI to NULL
UPDATE BORROW
SET BNAME=NULL
WHERE CNAME='KRANTI'
SELECT *FROM BORROW

--3) Display the name of borrowers whose amount is NULL.
SELECT *FROM BORROW WHERE AMOUNT IS NULL

--4) Display the Borrowers whose having branch
SELECT *FROM BORROW WHERE BNAME IS NOT NULL

--5) Update the Loan Amount to 5000, Branch to VRCE & Customer Name to Darshan whose loan no is 481.
UPDATE BORROW
SET AMOUNT=5000,BNAME='VRCE',CNAME='DARSHAN'
WHERE LOANNO=481
SELECT *FROM BORROW

--6) Update the Deposit table and set the date to 01-01-2021 for all the depositor whose amount is less than 2000
UPDATE DEPOSITE
SET ADATE='2021-1-1'
WHERE AMOUNT<2000
SELECT *FROM DEPOSITE

--7) Update the Deposit table and set the date to NULL & Branch name to ‘ANDHERI whose Account No is 110
UPDATE DEPOSITE 
SET ADATE=NULL,BNAME='ANDHERI'
WHERE ACTNO=110
SELECT *FROM DEPOSITE


