SELECT *FROM DEPOSITE
SELECT *FROM CUSTOMERS
SELECT *FROM BORROW
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSITE
SELECT LOANNO,AMOUNT FROM BORROW
SELECT *FROM BORROW WHERE BNAME='ANDHERI'
SELECT ACTNO,AMOUNT FROM DEPOSITE WHERE ACTNO=106
SELECT *FROM BORROW WHERE AMOUNT>5000
SELECT CNAME FROM DEPOSITE WHERE ADATE<'1996-12-1'
SELECT CNAME FROM DEPOSITE WHERE ACTNO<105
SELECT CNAME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI'
SELECT CNAME FROM CUSTOMERS WHERE CITY IN ('NAGPUR','DELHI')
SELECT CNAME,BNAME FROM DEPOSITE WHERE AMOUNT>4000 AND ACTNO<105
SELECT *FROM BORROW WHERE AMOUNT>3000 AND AMOUNT<=8000
SELECT *FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000
SELECT *FROM DEPOSITE WHERE NOT BNAME='ANDHERI'
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSITE WHERE BNAME=('AJNI''KAROLBAGH''M.G.ROAD') AND ACTNO<104
SELECT TOP 5 *FROM DEPOSITE
SELECT TOP 3 *FROM DEPOSITE WHERE AMOUNT>1000
SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME<> 'ANDHERI'
SELECT DISTINCT CITY FROM CUSTOMERS
--SELECT DISTINCT BNAME FROM BRANCH
SELECT TOP 50 PERCENT *FROM BORROW
SELECT TOP 25 PERCENT *FROM DEPOSITE WHERE AMOUNT>5000
SELECT DISTINCT CITY FROM CUSTOMERS
SELECT LOANNO,CNAME,BNAME,AMOUNT,AMOUNT+(AMOUNT*0.10) AS NEW_AMOUNT FROM BORROW
SELECT *FROM BORROW WHERE LOANNO%2=0 
SELECT *FROM BORROW WHERE LOANNO%2!=0 

